from .const import (
    ATTR_WATER_LEAK_STATUS,
    ATTR_BATT_ALERT,
    ATTR_BATTERY_STATUS,
    ATTR_BATTERY_VOLTAGE,
    ATTR_INTENSITY,
    ATTR_INTENSITY_MIN,
    ATTR_KEY_DOUBLE_UP,
    ATTR_KEYPAD,
    ATTR_LED_OFF_COLOR,
    ATTR_LED_OFF_INTENSITY,
    ATTR_LED_ON_COLOR,
    ATTR_LED_ON_INTENSITY,
    ATTR_LIGHT_WATTAGE,
    ATTR_PHASE_CONTROL,
    ATTR_RSSI,
    ATTR_STATUS,
    ATTR_TANK_PERCENT,
    ATTR_TEMP_ALARM,
    ATTR_TIMER,
    ATTR_WATTAGE_INSTANT,
    ATTR_WATER_LEAK_STATUS,
    ATTR_WIFI,
    ATTR_TEMP,
)
from .climate import IMPLEMENTED_DEVICE_MODEL as CLIMATE_MODEL
from .light import IMPLEMENTED_DEVICE_MODEL as LIGHT_MODEL
from .switch import IMPLEMENTED_DEVICE_MODEL as SWITCH_MODEL
from .valve import IMPLEMENTED_DEVICE_MODEL as VALVE_MODEL
from .sensor import IMPLEMENTED_DEVICE_MODEL as SENSOR_MODEL

# Combine all device models
ALL_MODEL = CLIMATE_MODEL + LIGHT_MODEL + SWITCH_MODEL + VALVE_MODEL
FULL_MODEL = CLIMATE_MODEL + LIGHT_MODEL + SWITCH_MODEL + VALVE_MODEL + SENSOR_MODEL

# Global sensor attributes for all devices
GLOBAL_ATTRIBUTES = [ATTR_RSSI]
GLOBAL_WIFI_ATTRIBUTES = [ATTR_WIFI]

LIGHT_MODEL = [2131, 2132, 2121]
SENSOR_LIGHT_GLOBAL = []
NUMBER_LIGHT_GLOBAL = [ATTR_INTENSITY, ATTR_INTENSITY_MIN, ATTR_LED_ON_INTENSITY, ATTR_LED_OFF_INTENSITY, ATTR_TIMER]
SELECT_LIGHT_GLOBAL = [ATTR_KEYPAD, ATTR_LED_ON_COLOR, ATTR_LED_OFF_COLOR]

DEVICE_MODEL_LIGHT = [2121]
SENSOR_DEVICE_MODEL_LIGHT = [ATTR_LIGHT_WATTAGE]

DEVICE_MODEL_DIMMER = [2131]
SENSOR_DEVICE_MODEL_DIMMER = [ATTR_LIGHT_WATTAGE]

DEVICE_MODEL_NEW_DIMMER = [2132]
SENSOR_DEVICE_MODEL_NEW_DIMMER = [ATTR_PHASE_CONTROL, ATTR_KEY_DOUBLE_UP, ATTR_WATTAGE_INSTANT]

SWITCH_MODEL = [2152, 2151, 2180, 2181, 2600, 2610, 2506]

IMPLEMENTED_WIFI_WATER_HEATER_LOAD_MODEL = [2152]
IMPLEMENTED_WATER_HEATER_LOAD_MODEL = [2151]
IMPLEMENTED_ZB_DEVICE_CONTROL = [2180]
IMPLEMENTED_SED_DEVICE_CONTROL = [2181]
IMPLEMENTED_WALL_DEVICES = [2600, 2610]
IMPLEMENTED_LOAD_DEVICES = [2506]

SENSOR_MODEL = [130, 5056, 5055, 5051, 5053, 4210, 42102, 5050, 5052]

IMPLEMENTED_GATEWAY = [130]
IMPLEMENTED_TANK_MONITOR = [5056]
IMPLEMENTED_LTE_TANK_MONITOR = [5055]
IMPLEMENTED_SENSOR_MODEL = [5051, 5053]
IMPLEMENTED_NEW_SENSOR_MODEL = [4210]
IMPLEMENTED_NEW_CONNECTED_SENSOR = [42102]
IMPLEMENTED_CONNECTED_SENSOR = [5050, 5052]

VALVE_MODEL = [3155, 3153, 51532, 3150, 3151]

IMPLEMENTED_WIFI_MESH_VALVE_MODEL = [3155]
SENSOR_WIFI_MESH_VALVE_MODEL_ATTRIBUTE = [ATTR_TEMP_ALARM, ATTR_BATTERY_STATUS, ATTR_BATTERY_VOLTAGE, ATTR_WATER_LEAK_STATUS]

IMPLEMENTED_ZB_MESH_VALVE_MODEL = [3153, 31532]
SENSOR_ZB_MESH_VALVE_MODEL_ATTRIBUTE = [ATTR_BATTERY_VOLTAGE, ATTR_BATTERY_STATUS, ATTR_WATER_LEAK_STATUS]

IMPLEMENTED_WIFI_VALVE_MODEL = [3150]
SENSOR_WIFI_VALVE_MODEL_ATTRIBUTE = [ATTR_TEMP_ALARM, ATTR_BATTERY_VOLTAGE, ATTR_BATTERY_STATUS, ATTR_WATER_LEAK_STATUS]
BINARY_SENSOR_WIFI_VALVE_MODEL_ATTRIBUTE = [ATTR_BATT_ALERT]
  
IMPLEMENTED_ZB_VALVE_MODEL = [3151]
SENSOR_ZB_VALVE_MODEL_ATTRIBUTE = [ATTR_BATTERY_VOLTAGE, ATTR_BATTERY_STATUS]


CLIMATE_MODEL = [7372, 739, 737, 738, 1510, 742, 1123, 1124, 7373, 300, 1512, 6810, 6811, 6812, 6727, 6730]

DEVICE_MODEL_LOW = [7372]
DEVICE_MODEL_LOW_WIFI = [739]
DEVICE_MODEL_FLOOR = [737]
DEVICE_MODEL_WIFI_FLOOR = [738]
DEVICE_MODEL_WIFI = [1510, 742]
DEVICE_MODEL_HEAT = [1123, 1124]
DEVICE_MODEL_DOUBLE = [7373]
DEVICE_MODEL_HEAT_G2 = [300]
DEVICE_MODEL_HC = [1512]
DEVICE_MODEL_HEAT_PUMP = [6810, 6811, 6812]
DEVICE_MODEL_HEAT_COOL = [6727, 6730]
