"""Constants for neviweb component."""

DOMAIN = "neviweb130"
CONF_NETWORK = 'network'

ATTR_SIGNATURE = "signature"
ATTR_POWER_MODE = "powerMode"
ATTR_INTENSITY = "intensity"
#ATTR_RSSI = "rssi"
ATTR_WATTAGE = "loadConnected"
ATTR_WATTAGE_INSTANT = "wattageInstant"
ATTR_WATTAGE_OVERRIDE = "wattageOverride"
ATTR_SETPOINT_MODE = "setpointMode"
ATTR_ROOM_SETPOINT = "roomSetpoint"
ATTR_ROOM_TEMPERATURE = "roomTemperature"
ATTR_OUTPUT_PERCENT_DISPLAY = "outputPercentDisplay"
ATTR_ROOM_SETPOINT_MIN = "roomSetpointMin"
ATTR_ROOM_SETPOINT_MAX = "roomSetpointMax"
ATTR_WATER_LEAK_STATUS = "waterLeakStatus"
ATTR_BATTERY_VOLTAGE = "batteryVoltage"

MODE_AUTO = "auto"
MODE_AUTO_BYPASS = "autoBypass"
MODE_MANUAL = "manual"
MODE_AWAY = "away"
MODE_OFF = "off"
