"""Constants for neviweb component."""

DOMAIN = "neviweb130"
CONF_NETWORK = 'network'

ATTR_SIGNATURE = "signature"
ATTR_POWER_MODE = "powerMode"
ATTR_ONOFF = "onOff"
ATTR_INTENSITY = "intensity"
ATTR_WATTAGE = "loadConnected"
ATTR_WATTAGE_INSTANT = "wattageInstant"
ATTR_WATTAGE_OVERRIDE = "wattageOverride"
ATTR_SETPOINT_MODE = "setpointMode"
ATTR_ROOM_SETPOINT = "roomSetpoint"
ATTR_ROOM_TEMPERATURE = "roomTemperature"
ATTR_OUTPUT_PERCENT_DISPLAY = "outputPercentDisplay"
ATTR_ROOM_SETPOINT_MIN = "roomSetpointMin"
ATTR_ROOM_SETPOINT_MAX = "roomSetpointMax"
ATTR_GFCI_STATUS = "gfciStatus"
ATTR_WATER_LEAK_STATUS = "waterLeakStatus"
ATTR_BATTERY_VOLTAGE = "batteryVoltage"
ATTR_LEVEL_STATUS = "tankLevelPercent"
ATTR_VALVE_STATUS = "valveAction"
ATTR_FLOOR_MODE = "airFloorMode"
ATTR_FLOOR_OUTPUT2 = "loadWattOutput2"
ATTR_FLOOR_AUX = "auxHeatConfig"
ATTR_FLOOR_OUTPUT1 = "loadWattOutput1"
ATTR_FLOOR_LOAD = "loadWatt"
ATTR_WIFI = "wifiRssi"

MODE_AUTO = "auto"
MODE_AUTO_BYPASS = "autoBypass"
MODE_MANUAL = "manual"
MODE_AWAY = "away"
MODE_OFF = "off"

STATE_WATER_LEAK = "water"
STATE_VALVE_STATUS = "closed"
