name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install build dependencies and isal system library
        run: |
          sudo apt-get update
          sudo apt-get install -y nasm libisal-dev python3-dev python3-pip python3-setuptools python3-wheel build-essential
      - name: Install Python isal package
        run: pip install isal
      # Add your build/test steps here
