name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install nasm and isal
        run: sudo apt-get update && sudo apt-get install -y nasm libisal-dev
