name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y nasm build-essential python3-dev python3-pip python3-setuptools python3-wheel

      - name: Check nasm
        run: |
          which nasm
          nasm -v

      - name: Install Python dependencies (including isal)
        run: |
          pip install --upgrade pip setuptools wheel
          pip install isal
