name: Test Neviweb130 Component

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -U pip
          pip install -e .[dev]

      - name: Run static checks
        run: |
          black --check .
          isort --check-only .
          flake8 .
          mypy custom_components/neviweb130

      - name: Run tests (if any)
        run: |
          pytest || echo "No tests defined yet"
